name: CI / Release

on:
  push:
    branches: [ master, main ]
    tags: [ 'v*' ]   # adjust if you tag differently
  pull_request:
    branches: [ master, main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  # Always run on branches/PRs (no packaging)
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-dependency-path: |
            **/*.csproj
            global.json

      - name: Resolve & detect target frameworks
        id: tfm
        uses: ./.github/actions/detect-tfms

      - name: Restore
        run: dotnet restore --nologo

      - name: Build
        run: dotnet build --no-restore --configuration Release --nologo

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal --nologo

  # Only runs when the push ref is a tag (packages + GitHub Release)
  package:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-dependency-path: |
            **/*.csproj
            global.json

      - name: Resolve & detect target frameworks
        id: tfm
        uses: ./.github/actions/detect-tfms

      - name: Restore
        run: dotnet restore --nologo

      - name: Build
        run: dotnet build --no-restore --configuration Release --nologo

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal --nologo

      - name: Pack (if configured)
        run: dotnet pack --no-build --configuration Release --nologo || true

      - name: Publish per TFM & RID
        uses: ./.github/actions/publish-tfms
        with:
          project_path: ${{ steps.tfm.outputs.project_path }}
          frameworks: ${{ steps.tfm.outputs.frameworks }}
          rids: |
            win-x64
            linux-x64
          repo_name: ${{ env.REPO_NAME }}
          self_contained: true
          copy_sidecars: |
            appsettings.json
            LICENSE
            README.md
          copy_dirs: |
            libs
            plugins

      - name: Create GitHub Release & upload assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.REPO_NAME }} ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          files: |
            ./*.zip
            **/bin/Release/*.nupkg
          fail_on_unmatched_files: false